@startuml
'https://plantuml.com/component-diagram

!theme toy

component "sidis" as sidis {
        portin "REST API Plans" as apiP
        portin "REST API Subscriptions" as apiS
        portin "REST API Users" as apiU
}

interface "HTTP Client" as HTTP




HTTP -- apiP
HTTP -- apiS
HTTP -- apiU


@enduml