@startuml
'https://plantuml.com/component-diagram

!theme toy

component "sidis" {
    portin "REST API Plans" as apiP
    portin "REST API Subscriptions" as apiS
    portin "REST API Users" as apiU
    component "Plans" as plans
    component "Subscriptions" as subscriptions
    component "Users" as users
}

interface "HTTP Client" as HTTP

apiP --> plans
apiS --> subscriptions
apiU --> users

HTTP --- apiP
HTTP --- apiS
HTTP --- apiU

@enduml