@startuml

'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods


class Plans #ECFFDC/F8DE7E{
    name
    numberMinutes
    maxNumberDevices
    musicCollections
    musicSuggestions
    monthlyFee
    annualFee
    plansID
    isActive
}

class Subscriptions #ECFFDC/F8DE7E{
    plan
    subscriberID
    subscriptionID
    initialDate
    isActive
    finalDate
    feeType
    paymentMethod
    numberDevices
}




class AuthorityRole #ECFFDC/F8DE7E{
    authority
}

class User #ECFFDC/F8DE7E{
    username
    password
    id
    name
    role
    citizenCardNumber
    birthday
    phoneNumber
    sex
}

Plans "1" -down-  "*..1" Subscriptions:contains <

User "1" -down-  "*..1" Plans:works with >
AuthorityRole "1" -left- "*..1" User:has <
User "1" -down-  "*..1"Subscriptions:manages/contains >



@enduml
